<?php
// $Id$
function hosting_client_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql' :
    case 'mysqli':
      db_query("CREATE TABLE {hosting_client} (
        vid int(10) unsigned NOT NULL default '0',
        nid int(10) unsigned NOT NULL default '0',
        name longtext,
        organization longtext,
        email varchar(255) NOT NULL default '',
        PRIMARY KEY  (vid)
      ) /*!40100 DEFAULT CHARACTER SET UTF8 */ ");
      break;
   }

}
