<?php
/**
 * @file
 *   Defines package node types
 *
 * Packages are somewhat analogous to Drupal.org projects. i.e.: components that
 * can be installed onto Drupal sites.
 */

require_once 'hosting_package.instance.inc';

function _hosting_package_types() {
  return array(
    'profile' => t('Installation Profiles'),
    'module' => t('Modules'),
    'theme' => t('Themes'),
  );
}

/**
 * Implements hook_node_info().
 */
function hosting_package_node_info() {
  #package management
  $types["package"] =  array(
    "type" => 'package',
    "name" => t('Package'),
    'base' => 'hosting_package',
    "has_title" => FALSE,
    "title_label" => '',
    "description" => hosting_node_help("package"),
    "has_body" => 0,
    "body_label" => '',
    "min_word_count" => 0,
  );

  return $types;
}

/**
 * Implements hook_menu().
 */
function hosting_package_menu() {
  $items = array();

  $items['node/%hosting_package_wildcard/packages'] = array(
    'title' => 'Packages',
    'description' => 'List of packages available for this platform',
    'page callback' => 'hosting_package_list',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('view package'),
    'weight' => 1,
  );
  $items['node/%hosting_package_wildcard/packages/all'] = array(
    'title' => 'All packages',
    'description' => 'List of all packages',
    'page callback' => 'hosting_package_list',
    'page arguments' => array(1),
    'access arguments' => array('view package'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
  $x = 0;
  foreach (_hosting_package_types() as $type => $description) {
    $items['node/%hosting_package_wildcard/packages/' . $type] = array(
      'title' => $description,
      'description' => $description,
      'page callback' => 'hosting_package_list',
      'page arguments' => array(1, $type),
      'access arguments' => array('view package'),
      'type' => MENU_LOCAL_TASK,
      'weight' => $x++,
    );
  }
  return $items;
}

/**
 * Menu wildcard loader callback.
 *
 * Loads a hosting_site or hosting_platform node.
 * @see hosting_package_menu().
 *
 * @arg $arg a numeric nid
 */
function hosting_package_wildcard_load($arg) {
  if (!is_numeric($arg)) {
    return FALSE;
  }
  if ($node = node_load($arg)) {
    if (in_array($node->type, array('site', 'platform'))) {
      return $node;
    }
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function hosting_package_permission() {
  return array(
    'create package' => array(
      'title' => t('create package'),
      'description' => t('TODO Add a description for \'create package\''),
    ),
    'view package' => array(
      'title' => t('view package'),
      'description' => t('TODO Add a description for \'view package\''),
    ),
    'edit package' => array(
      'title' => t('edit package'),
      'description' => t('TODO Add a description for \'edit package\''),
    ),
    'delete package' => array(
      'title' => t('delete package'),
      'description' => t('TODO Add a description for \'delete package\''),
    ),
  );
}

/**
 * Implements hook_node_access().
 */
function hosting_package_node_access($node, $op, $account) {
  switch ($op) {
    case 'create':
      return user_access('create package', $account);
      break;
    case 'view':
      return user_access('view package', $account);
      break;
    case 'update':
      return user_access('edit package', $account);
      break;
    case 'delete':
      return user_access('delete package', $account);
      break;
    default:
      break;
  }
}

function hosting_get_profiles($platform = NULL, $field = 'title') {
  $profiles = array();
  if (!is_null($platform)) {
    $instances = hosting_package_instances_load(array(
      'i.rid' => $platform,
      'p.package_type' => 'profile',
      'n.status' => 1,
    ));

    foreach ($instances as $iid => $instance) {
      $profiles[$instance->package_id] = $instance->$field;
    }
  }
  else {
    $instances = hosting_package_instances_load(array(
      'p.package_type' => 'profile',
      'n.status' => 1,
      'r.type' => 'platform',
    ));

    foreach ($instances as $iid => $instance) {
      $profiles[$instance->package_id] = $instance->$field;
    }
  }

  return $profiles;
}

function hosting_get_profile_platforms($profile, $check_old_short_name = FALSE) {
  $defaults = array('default', 'standard', 'minimal', 'testing');

  $platforms = array();
  $instances = hosting_package_instances_load(array(
    'i.package_id' => $profile,
    'n.status' => 1,
    'r.status' => 1,
    'r.type' => 'platform',
  ));

  if ($check_old_short_name) {
    $instances = array_merge($instances, hosting_package_instances_load(array(
      'p.old_short_name' => $instances[key($instances)]->short_name,
      'n.status' => 1,
      'r.status' => 1,
      'r.type' => 'platform',
    )));
  }
  foreach ($instances as $iid => $instance) {
    $platform = node_load($instance->rid);
    // this is one of the default profiles
    if (in_array($instance->short_name, $defaults) &&
      sizeof(array_diff(array_values($platform->profiles), $defaults)) &&
      variable_get('hosting_ignore_default_profiles', FALSE)) {
      // there are other profiles available on this platform. skip this.
      continue;
    }
    if ($platform->platform_status != HOSTING_PLATFORM_DELETED) {
      $platforms[$instance->rid] = $platform->title;
    }
  }

  return $platforms;
}

function hosting_get_profile_languages($profile = NULL, $platform = NULL) {
  $languages['en'] = _hosting_language_name('en');
  if ($profile && $platform) {
    $instance = hosting_package_instance_load(array(
      'i.rid' => $platform,
      'i.package_id' => $profile,
    ));
    $languages = array_merge($languages, $instance->languages);
  }
  else {
    $result = db_query("SELECT DISTINCT language FROM {hosting_package_languages}");
    while ($lang = $result->fetch()) {
      $languages[$lang->language] = _hosting_language_name($lang->language);
    }
  }
  return $languages;
}

/**
 * A generic method for finding whichever packages you are looking for.
 *
 * This works similarly to node_load's implementation, but it will only look
 * for fields related to packages.
 *
 * @param
 *    An associated array containing the following properties
 *    - name => A string containing the friendly name of the package
 *    - short_name => The name of the drupal package in the system table
 *    - old_short_name => The name that a package used to be called, for
 *      migration purposes.
 *    - package_type => The type of package. (theme|module|profile|engine)
 */
function _hosting_package_load($param) {
  // Turn the conditions into a query.
  foreach ($param as $key => $value) {
    $cond[] = 'p.' . db_escape_table($key) . " = '%s'";
    $arguments[] = $value;
  }
  $cond = implode(' AND ', $cond);
  // TODO convert this statement to a DBTNG dynamic query.
  $result = db_query('SELECT n.nid FROM {node} n left join {hosting_package} p on n.nid = p.nid WHERE ' . $cond, $arguments);
  while ($nid = $result->fetch()) {
    $return[$nid->nid] = node_load($nid->nid);
  }
  if (sizeof($return)) {
    return $return;
  }
  return NULL;
}

function hosting_get_packages_by_type($type) {
  $result = db_query("SELECT nid FROM {hosting_package} WHERE package_type = :package_type", array(':package_type' => $type));

  if ($nid = $result->fetchField()) {
    return node_load($nid);
  }
  return FALSE;
}

function hosting_get_default_profile($default = NULL) {
  if ($p = hosting_get_package(variable_get('hosting_default_profile', 'default'))) {
    return $p->nid;
  }
  elseif ($p = hosting_get_package('standard')) {
    return $p->nid;
  }
  return $default;
}

function hosting_get_package($short_name) {
  $result = db_query("SELECT nid FROM {hosting_package} WHERE short_name = :short_name", array(':short_name' => $short_name));
  if ($nid = $result->fetchField()) {
    return node_load($nid);
  }
  return FALSE;
}

/**
 * Implements hook_insert().
 */
function hosting_package_insert($node) {
  $id = db_insert('hosting_package')
    ->fields(array(
      'vid' => $node->vid,
      'nid' => $node->nid,
      'package_type' => $node->package_type,
      'short_name' => $node->short_name,
      'old_short_name' => $node->old_short_name,
      'description ' => $node->description,
    ))
    ->execute();
}


/**
 * Implements hook_update().
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function hosting_package_update($node) {
  // if this is a new node or we're adding a new revision,
  if (!empty($node->revision)) {
    hosting_package_insert($node);
  }
  else {
    db_update('hosting_package')
      ->fields(array(
        'package_type' => $node->package_type,
        'short_name' => $node->short_name,
        'old_short_name' => $node->old_short_name,
        'description' => $node->description,
      ))
      ->condition('nid', $node->nid)
      ->execute();
  }
}

function hosting_nodeapi_package_delete_revision(&$node) {
  db_delete('hosting_package')
    ->condition('vid', $node->vid)
    ->execute();
}

/**
 * Implements hook_delete().
 */
function hosting_package_delete($node) {
  db_delete('hosting_package')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_load().
 */
function hosting_package_load($nodes) {
  foreach ($nodes as $nid => &$node) {
    $additions = db_query('SELECT package_type, short_name, old_short_name, description FROM {hosting_package} WHERE vid = :vid', array(':vid' => $node->vid))->fetch();
    foreach ($additions as $property => &$value) {
      $node->$property = $value;
    }
  }
}

/**
 * Implements hook_view().
 */
function hosting_package_view($node, $teaser = FALSE, $page = FALSE) {
  hosting_set_breadcrumb($node);
  $node->content['info']['#prefix'] = '<div id="hosting-package-info">';
  $node->content['info']['package_type'] = array(
    '#type' => 'item',
    '#title' => t('Package Type'),
    '#markup' => filter_xss($node->package_type),
  );
  $node->content['info']['short_name'] = array(
    '#type' => 'item',
    '#title' => t('Project Name'),
    '#markup' => filter_xss($node->short_name),
  );

  if (!empty($node->old_short_name)) {
    $node->content['info']['old_short_name'] = array(
      '#type' => 'item',
      '#title' => t('Previous Project Name'),
      '#markup' => filter_xss($node->old_short_name),
    );
  }
  $node->content['info']['#suffix'] = '</div>';

  if ($node->package_type == 'profile') {
    $node->content['sites_view'] = array(
      '#type' => 'item',
      '#markup' => drupal_render(drupal_get_form('hosting_site_list_form', 'profile', $node->nid)),
      '#prefix' => '<div id="hosting-site-list">',
      '#suffix' => '</div>',
      '#weight' => 10,
    );
  }
  else { // For modules & themes
    $node->content['hosting-package-usage'] = array(
      '#prefix' => '<div id="hosting-package-usage">',
      '#suffix' => '</div>',
      '#markup' => drupal_render(_hosting_package_list_package_usage($node)),
      '#weight' => 99,
    );
  }
  return $node;
}

/**
 * Return a themed table showing where a package is used.
 */
function _hosting_package_list_package_usage($node) {
  $header = array(
    array(
      'data' => t('Package version'),
      'field' => 'package_version',
      'sort' => 'DESC',
    ),
    array(
      'data' => t('Platform'),
      'field' => 'platform_name',
    ),
    array(
      'data' => t('Site'),
      'field' => 'site_name',
    ),
  );
/*
  $sql = "SELECT s.client AS client_nid,
            n2.title AS platform_name,
            s.platform AS platform_nid,
            n.title AS site_name,
            n.nid AS site_nid,
            pi.version AS package_version
          FROM {node} AS n
            LEFT JOIN {hosting_package_instance} AS pi ON (pi.rid = n.nid)
            LEFT JOIN {hosting_package} AS p ON (p.nid = pi.package_id)
            LEFT JOIN {hosting_site} AS s ON (s.nid = n.nid)
            LEFT JOIN {node} AS n2 ON (n2.nid = s.platform)
          WHERE pi.status=1 AND s.status >= " . HOSTING_SITE_DISABLED . " AND pi.package_id=%d";

  $sql .= tablesort_sql($header);
  $result = pager_query(db_rewrite_sql($sql, 'n'), 100, 2, null, array($node->nid));
*/
  // TODO: Validate conversion to DBTNG.
  $query = db_select('node', 'n')
    ->extend('PagerDefault')
    ->extend('TableSort');
  $query->join('hosting_package_instance', 'pi', 'pi.rid = n.nid');
  $query->join('hosting_package', 'p', 'p.nid = pi.package_id');
  $query->join('hosting_site', 's', 's.nid = n.nid');
  $query->join('node', 'n2', 'n2.nid = s.platform');
  $query = $query->element(2);
  $query->addField('s', 'client', 'client_nid');
  $query->addField('n2', 'title', 'platform_name');
  $query->addField('s', 'platform', 'platform_nid');
  $query->addField('n', 'title', 'site_name');
  $query->addField('n', 'nid', 'site_nid');
  $query->addField('pi', 'version', 'package_version');
  $query = $query
    ->condition('pi.status', 1)
    ->condition('s.status', HOSTING_SITE_DISABLED, '>=')
    ->condition('pi.package_id', $node->nid)
    ->limit(100)
    ->orderByHeader($header)
    ->addTag('node_access');
  $result = $query->execute();

  if (!$result) {
    return t('No packages are associated with @reference', array('@reference' => $node->title));
  }
  $rows = array();
  while ($package = $result->fetch()) {
    $rows[] = array('data' => array(
        $package->package_version,
        l(filter_xss($package->platform_name), 'node/' . $package->platform_nid),
        l(filter_xss($package->site_name), 'node/' . $package->site_nid),
      ));
  }

  return theme('table', array('header' => $header, 'rows' => $rows)) . theme('pager', array('tags' => NULL, 'element' => 2));
}

/**
 * Implements hook_hosting_site_site_list_filters().
 */
function hosting_package_hosting_site_site_list_filters() {
  return array('profile');
}

/**
 * Return names of the languages available
 */
function _hosting_language_names($languages) {
  foreach ($languages as $language) {
    // Try to use verbose language name
    $return[$language] = _hosting_language_name($language);
  }
  return $return;
}

function _hosting_language_name($language) {
  include_once DRUPAL_ROOT . '/includes/iso.inc';
  $locales = _locale_get_predefined_list();
  return $locales[$language][0] . (isset($locales[$language][1]) ? ' ' . t('(@language)', array('@language' => $locales[$language][1])) : '');
}


function _hosting_package_plural_map($key = NULL) {
  static $plural_map = array(
    'modules' => 'module',
    'themes' => 'theme',
    'profiles' => 'profile',
    'engines' => 'engine',
    'platforms' => 'platform',
  );
  if (is_null($key)) {
    return $plural_map;
  }
  return (array_key_exists($key, $plural_map)) ? $plural_map[$key] : $key;
}

/**
 * Sync the package and package release nodes with the information
 * retrieved from the verify task
 *
 * @todo Make this prettier.
 */
function hosting_package_sync(&$data) {
  foreach ($data as $plural => $packages) {
    $type = _hosting_package_plural_map($plural);
    foreach ($packages as $short_name => $file) {
      $name = isset($file['info']['name']) ? $file['info']['name'] : $short_name;
      if (!($package = hosting_get_package($short_name))) {
        // Create a new package.
        $package = new stdClass();
        $package->type = 'package';
        $package->uid = 1;
        $package->package_type = $type;
        $package->short_name = $short_name;
        $package->old_short_name = isset($file['info']['old_short_name']) ? $file['info']['old_short_name'] : '';
        $package->status = 1;
      }

      // we only call node save when the title, description changes
      // or when it's a new package.
      if (!isset($package->nid) ||
        (isset($package->title) && ($package->title != $name)) ||
        (isset($file['info']['description']) && ($package->description != $file['info']['description'])) ||
        (isset($file['info']['old_short_name']) && ($package->old_short_name != $file['info']['old_short_name']))) {

        $package->title = $name;
        $package->description = isset($file['info']['description']) ? $file['info']['description'] : '';
        $package->old_short_name = isset($file['info']['old_short_name']) ? $file['info']['old_short_name'] : '';

        node_save($package);
      }
      $data[$plural][$short_name]['package_id'] = $package->nid;
    }
  }
}

/**
 * Display a list of packages associated to a node
 * @TODO Add ability to filter by additional fields
 * @TODO Add paging.
 */
function hosting_package_list($ref, $type = NULL) {
  drupal_set_title(t('Packages on @reference', array('@reference' => $ref->title)), PASS_THROUGH);
  $header = array(
    array(
      'data' => t('Status'),
      'field' => 'status',
      'sort' => 'DESC',
    ),
    array(
      'data' => t('Package'),
      'field' => 'short_name',
    ),
    array(
      'data' => t('Release'),
      'field' => 'version',
    ),
    array(
      'data' => t('Package type'),
      'field' => 'package_type',
    ),
  );
/*
  $args[] = $ref->nid;

  if (!is_null($type)) {
    $cond = " AND h.package_type = '%s'";
    $args[] = $type;
  }

  $sql = "SELECT h.nid as 'package', i.status, h.short_name, i.version, h.package_type, i.status FROM {hosting_package} h
    LEFT JOIN {hosting_package_instance} i ON i.package_id=h.nid WHERE i.rid=%d" . $cond;
  $sql .= tablesort_sql($header);
  $result = pager_query(db_rewrite_sql($sql, 'h'), 25, 2, null, $args);
*/
  // TODO: Validate conversion to DBTNG.
  $query = db_select('hosting_package', 'h')
    ->extend('PagerDefault')
    ->extend('TableSort');
  $query->join('hosting_package_instance', 'i', 'i.package_id=h.nid');
  $query = $query->element(2);
  $query->addField('h', 'nid', 'package');
  $query = $query
    ->fields('i', array('status', 'version'))
    ->fields('h', array('short_name', 'package_type'))
    ->condition('i.rid', $ref->nid);
  if (!is_null($type)) {
    $query = $query->condition('h.package_type', $type);
  }
  $query = $query
    ->limit(25)
    ->orderByHeader($header)
    ->addTag('node_access');
  // @TODO hide deleted sites
  $result = $query->execute();

  $view_package_perm = user_access('view package');

  if (!$result) {
    return t('No packages are associated with @reference', array('@reference' => $ref->title));
  }
  $rows = array();
  while ($package = $result->fetch()) {
    $row_class = ($package->status == 1) ? 'hosting-success' : 'hosting-info';
    $row = array();
    $row[] =  array(
      'data' => ($package->status) ? t('Enabled') : t('Available'),
      'class' => array('hosting-status'),
    );
    $row[] =  ($view_package_perm) ? l(filter_xss($package->short_name), 'node/' . $package->package) : $package->short_name;
    $row[] =  $package->version;
    $row[] = filter_xss($package->package_type);
    $rows[] = array(
      'data' => $row,
      'class' => array($row_class),
    );
  }

  return theme('table', array('header' =>   $header, 'rows' => $rows, 'attributes' => array('class' => array('hosting-table')))) . theme('pager', array('tags' => NULL, 'element' => 2));
}

/**
 * Implements hook_views_api().
 */
function hosting_package_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'hosting_package'),
  );
}
