language: generic

sudo: required

env:
  globaL:
    - DOCKER_VERSION=1.11.2-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1
    - AEGIR_HOSTING_VERSION=7.x-3.x
    - AEGIR_TESTS_VERSION=master

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.travis
    - sitetest.aegir.travis

services:
  - docker

before_install:
  # Show travis build dir variable.
  - echo $TRAVIS_BUILD_DIR

  # Get test scripts
  - git clone http://github.com/aegir-project/tests.git /home/travis/build/aegir-project/tests
  - cd /home/travis/build/aegir-project/tests
  - git checkout $AEGIR_TESTS_VERSION

  # Get Hosting
  - git clone http://git.drupal.org/project/hosting.git /home/travis/build/aegir-project/hosting
  - cd /home/travis/build/aegir-project/hosting
  - git checkout $AEGIR_HOSTING_VERSION


  # Run prepare scripts.
  - cd /home/travis/build/aegir-project/tests/travis
  - sudo bash prepare-docker.sh
  - bash prepare-testenv.sh

script:

  # Tests are included in the docker-compose.yml file in the tests repo.
  - sudo docker-compose -f docker-compose-hostmaster.yml run hostmaster
