<?php

function hosting_install() {
  # Configuration template table
  db_query("CREATE TABLE {hosting_config_template} (
    tid int NOT NULL auto_increment,
    vid int NOT NULL default '0',
    type varchar(16) NOT NULL default '',
    template longtext NOT NULL,
    status tinyint unsigned NOT NULL default '0',
    timestamp int NOT NULL default '0',
    PRIMARY KEY (tid),
    KEY (type)
  ) /*!40100 DEFAULT CHARACTER SET UTF8 */ ");

}

