<?php
// $Id$

/**
 * @file
 * Provision module overrides for Apache-ITK
 *
 */

/**
 * TODO: We probably need some settings in here: http://drupal.org/node/82967
 */
define(GID_BASE, 5000);

/**
 * Implementation of hook_provision_args()
 *
 * The idea here is to override the webgroup while still keeping it for the
 * user.
 */
function hosting_itk_provision_args($node, $task = '') {
  $values = array();
  if ($node->type == 'site') {
    $values['load-provision-itk'] = TRUE;
    $platform = node_load($node->platform);
    if ($platform) {
      $web_server = node_load($platform->web_server);
      $values['web_user'] = $web_server->web_group;
    }
    $values['web_group'] = $node->client + GID_BASE;
  }
  return $values;
}
