<?php

function hosting_clone_hosting_tasks() {
  $options = array();

  $options['site']['clone'] = array(
    'title' => t('Clone'),
    'description' => t('Copy the site to a new platform.'),
    'weight' => 5
  );
  return $options;
}

function hosting_clone_perm() {
  return array(
    'create clone task',
  );
}

function hosting_task_clone_form_validate($form, &$form_state) {
  if (!$form_state['values']['parameters']['hidden'] && !$form_state['values']['parameters']['target_platform']) {
    form_set_error('parameters][target_platform', t('You need to select a valid platform to migrate your site to.'));
  }
  $url = strtolower($form_state['values']['parameters']['new_name']); // domain names are case-insensitive
  if (!_hosting_valid_fqdn($url)) {
    form_set_error('title', t("You have not specified a valid url for this site."));
  }
  if (hosting_site_exists($url)) {
    form_set_error('title', t("The domain name you have specified is not unique."));
  }

}

function hosting_clone_theme($existing, $type, $theme, $path) {
  return array('hosting_task_clone_form' => array('arguments' => array('form' => NULL)));
}

function hosting_task_clone_form($node) {
  $form = hosting_task_migrate_form($node);
  $form['new_name'] = array (
    '#title' => t('New site name'),
    '#type' => 'textfield',
    '#weight' => '-1',
    '#required' => TRUE,
    '#default_value' => $node->title
  );
  return $form;
}

function theme_hosting_task_clone_form(&$form) {
  return theme_hosting_task_migrate_form($form);
}

