<?php
/**
 * @file Web server node type is defined here.
 */

/**
 * Implementation of hook_hosting_service()
 */
function hosting_web_server_hosting_service() {
  return array(
    'http' => 'apache', 
  );
}

function hosting_web_server_hosting_service_type() {
  return array(
    'http' => array(
      'title' => t('Web'),
    ),
  );
}

/**
 * "Feature" definition
 *
 * @see hosting.features.inc
 */
function hosting_web_server_hosting_feature() {
  $features['ports'] = array(
    'title' => t('Ports'),
    'description' => t('Allow configuration of multiple ports per server and non-default ports for sites.'),
    'status' => HOSTING_FEATURE_ENABLED,
  );
  return $features;
}
