<?php
/**
 * @file Web server node type is defined here.
 */
include_once('hosting_web_server.help.inc');

/**
 * Implementation of hook_hosting_service()
 *
 * @see hosting_help_requirements()
 */
function hosting_web_server_hosting_service() {
  return array( "http" => array(
    'title' => t("Web server"),
    'type' => 'Apache', 
    'class' => 'hostingService_HTTP',
    'module' => 'hosting_web_server',
    'file' => 'hosting_web_server.service.inc'
  ));
}

/**
 * "Feature" definition
 *
 * @see hosting.features.inc
 */
function hosting_web_server_hosting_feature() {
  $features['ports'] = array(
    'title' => t('Ports'),
    'description' => t('Allow configuration of multiple ports per server and non-default ports for sites.'),
    'status' => HOSTING_FEATURE_ENABLED,
  );
  return $features;
}

/**
 * Small helper function to get web servers.
 *
 * @return array pairs of nid -> title of enabled webservers
 */ 
function _hosting_get_web_servers() {
  $return = array();
  $result = db_query("SELECT n.nid, n.title FROM {node} n LEFT JOIN {hosting_service} s ON n.vid=s.vid AND s.available=1 WHERE s.service='http'");
  while($server = db_fetch_object($result)) {
    $return[$server->nid] = $server->title;
  }
  return $return;
}

