<?php

function hosting_migrate_hosting_tasks($type, $task = null) {
  $options = array();

  if ($type == 'site') {
    $options['migrate'] = array(
      'title' => t('Migrate'),
      'description' => t('Move the site to a new platform.'),
      'weight' => 7
    );
  }
  return $options;
}


function hosting_migrate_perm() {
  return array(
    'create migrate task',
  );
}

function hosting_migrate_menu() {
  // TODO: add some security here
  $items['hosting/migrate/compare'] = array(
    'title' => 'Compare packages',
    'page callback' => 'hosting_migrate_comparison',

    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );


  return $items;
}



function hosting_task_migrate_form_validate($form, &$form_state) {
  if (!$form_state['values']['parameters']['target_platform'] || $form_state['values']['parameters']['hidden']) {
    form_set_error('parameters][target_platform', t('You may not select your current platform to migrate your site to.'));
  }
}

function hosting_migrate_theme($existing, $type, $theme, $path) {
  return array(
  'hosting_migrate_comparison' => array(
      'arguments' => array('packages')
  ));
}

function hosting_task_migrate_form($node) {

  $packages = array();

  $profile_platform_instances = hosting_package_instances_load(
    array('r.type' => 'platform', 'n.nid' => $node->profile));
  if (sizeof($profile_platform_instances) <= 1) {
    $form['no_targets'] = array(
      '#value' => t('<br />There are no platforms that can meet the dependencies for this site<br />'));
    $form['hidden'] = array(
      '#type' => 'hidden',
      '#value' => t('no_targets')); 
  }
  $site_platform = node_load($node->platform);

  $form[$node->platform]['target_platform'] = array(
    '#type' => 'radio',
    '#title' => $site_platform->title,
    "#return_value" => $node->platform,
    "#default_value" => $node->platform,
    '#description' => t("Current platform"),
    '#parents' => array('parameters', 'target_platform'),
    '#disabled' => TRUE,
  );
  foreach ($profile_platform_instances as $profile_instance) {
    if ($profile_instance->rid != $node->platform) {
      $status = hosting_package_comparison($node->nid, $profile_instance->iid);

      $description = t("Upgrades: !upgrades, Warnings: !missing, Errors: !errors | <a href='!url'>Compare platforms</a>",
        array(
          '!upgrades' => $status['upgrade'],
          '!missing' => $status['missing'],
          '!errors' => $status['error'],
          '!url' => url('hosting/migrate/compare/' . $node->nid . '/' . $profile_instance->iid))
        );
      $platform = node_load($profile_instance->rid);
      if ($platform->web_server == $site_platform->web_server) {

        $form[$platform->nid]['target_platform'] = array(
          '#type' => 'radio',
          '#title' => $platform->title,
          '#parents' => array('parameters', 'target_platform'),
          "#return_value" => $platform->nid,
          '#description' => $description,
        );
      }
      if ($status['error']) {
        $form[$platform->nid]['target_platform']['#disabled'] = TRUE;
      }

    }
  }

  $form['#node'] = $node;
  return $form;
  $table = array();

  if (sizeof($options)) {
    $form['target_platform'] = array(
      '#type' => 'radios',
      '#title' => t('Migrate to'),
      '#options' => $options,
      '#required' => TRUE
    );
  }
  else {
    $form['target_text'] = array('#type' => 'item',
      '#value' => t('<strong>No valid platforms to migrate to.</strong>')
    );
  }
  return $form;
}

function hosting_migrate_comparison($current, $target) {

  _hosting_package_temporary_table("current", $current);
  _hosting_package_temporary_table("target", $target);

  $packages = array();

  $result = db_query("SELECT c.nid, c.short_name, 
    c.version as current_version, t.version as target_version,
    c.version_code as current_version_code, t.version_code as target_version_code,
    c.schema_version as current_schema, t.schema_version as target_schema FROM current c LEFT JOIN target t ON c.nid=t.nid ORDER BY short_name"); 

  while ($obj = db_fetch_object($result)) {
    if (is_null($obj->target_version_code)) {
      $obj->status = 'missing';
    }
    elseif (  ($obj->current_version_code > $obj->target_version_code) 
      || ($obj->current_schema > $obj->target_schema)) {
      $obj->status = 'downgrade';
    }
    elseif ($obj->current_version_code < $obj->target_version_code) {
      $obj->status = 'upgrade';
    }
    else {  
      $obj->status = 'same';
    }
    $packages[$obj->nid] = $obj;
  }
  
  db_query("DROP TEMPORARY TABLE target");
  db_query("DROP TEMPORARY TABLE current");

  return theme("hosting_migrate_comparison", $packages);
}

function _hosting_migrate_version_display($version, $schema = null, $status = null) {
  
  $status = (!is_null($status)) ? $status : 'same';
  $display = $version;
  if ($schema) {
    $display .= " (" . $schema . ")";
  }


  if ($status == 'missing') {
    $display = t('Missing');
  }
  return array('class' => 'hosting-package-' . $status, 'data' => $display);
}

function theme_hosting_migrate_comparison($packages) {
  $rows = array();

  $headers = array(t("Package"), t("Current"), t("Target"));
  foreach ($packages as $key => $instance) {
    $row = array();
    $row[] = $instance->short_name;

    $row[] = _hosting_migrate_version_display($instance->current_version, $instance->current_schema);
    $row[] = _hosting_migrate_version_display($instance->target_version, $instance->target_schema, $instance->status);
    $rows[] = $row;
  }
  $link = l(t('Back to site'), 'node/' . arg(3));
  return "<div id='hosting-package-comparison'>" . theme('table', $headers, $rows) . $link . "</div>";
}
