<?php

/**
 * @file
 * SSL certificate management frontend
 */

function hosting_ssl_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    if (isset($form['#node']->ssl)) {
      $default = array($form['#node']->ssl);
    }
    else {
      $default = array();
    }    
    $form['port']['ssl'] = array('#type' => 'checkbox', '#title' => 'Enable SSL encryption', '#default_value' => $default, '#weight' => 4, '#attributes' => array('onClick' => '$("#edit-port-80").attr("checked", !this.checked);$("#edit-port-443").attr("checked", this.checked);'),);
    $form['port']['#title'] = t("Port and encryption");
  }
}

function hosting_ssl_nodeapi(&$node, $op, $teaser, $page) {
  switch($op) {
    case 'view':
      if ($node->type == 'site') {
        $node->content['info']['ssl'] = array('#type' => 'item', '#title' => 'SSL encryption', '#value' => ( $node->ssl ? t('Enabled') : t('Disabled') ));
      }
      break;
  }
}