<?php

function hosting_platform_install() {  
  db_query("CREATE TABLE {hosting_platform} (
    vid int(10) unsigned NOT NULL default '0',
    nid int(10) unsigned NOT NULL default '0',
    publish_path longtext,
    web_server int(11) NOT NULL default '0',
    release_id int(11) NOT NULL default '0',
    verified int(11) NOT NULL default '0',
    PRIMARY KEY  (vid)
  ) /*!40100 DEFAULT CHARACTER SET UTF8 */ ");
}
