<?php
/**
 * @file
 *   Manage DNS records for your hosted sites.
 */

/**
 * Implements hook_hosting_service_type().
 */
function hosting_dns_hosting_service_type() {
  return array('dns' => array('title' => t('DNS service')));
}

/**
 * Implements hook_hosting_service().
 */
function hosting_dns_hosting_service() {
  return array(
    'dnsmasq' => 'dns',
    'bind' => 'dns',
    'bind_slave' => 'dns',
  );
}


