<?php

/**
 * Implementation of hook_hosting_service()
 */
function hosting_db_server_hosting_service() {
  return array(
    'db' => 'MySQL',
  );
}

function hosting_db_server_hosting_service_type() {
  return array(
    'db' => array(
      'title' => t('Database'),
    ),
  );
}

/**
 * Find the database server()
 */
function hosting_get_db_server($hostname, $web_server = null) {
  if (_hosting_valid_ip($hostname)) {
    $ip = $hostname;
    $hostname = gethostbyaddr($hostname);
  }
  else {
    $ip = gethostbyname($hostname);
  }
  $result = db_result(db_query("SELECT nid FROM {node} WHERE title in ('%s', '%s') and type='server'", $ip, $hostname));
  if ($result) {
    return node_load($result);
  }

  return false;
}


/**
 * Small helper function to get db servers.
*/ 
function _hosting_get_db_servers() {
  $return = array();
  $result = db_query("SELECT n.nid, n.title FROM {node} n LEFT JOIN {hosting_service} s ON n.vid=s.vid AND s.available=1 WHERE s.service='db'");
  while($server = db_fetch_object($result)) {
    $return[$server->nid] = $server->title;
  }
  return $return;
}

/**
 * Implementation of hook_nodeapi() presave for server node type.
 */
function hosting_db_server_nodeapi_server_presave(&$node) {
  if (empty($node->db_passwd) && $node->nid) {
    $old = node_load($node->nid);
    $node->db_passwd = $old->db_passwd;
  }
}

/**
 * Views integration
 */
function hosting_db_server_views_api() {
  return array(
    'api' => 2, 
    'path' => drupal_get_path('module', 'hosting_db_server'),
  );
}

