<?php

/**
 * Implementation of hook_menu
 */
function hosting_queue_runner_menu() {
  $items['admin/hosting/queue_runner'] = array(
    'title' => 'Queue runner settings',
    'description' => 'Configure the daemonized tasks queue runner.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_queue_runner_settings_form'),
    'access arguments' => array('administer hosting queues'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'hosting_queue_runner.admin.inc',
  );
  return $items;
}
