<?php

/**
 * @file
 * SSL certificate management frontend
 */

function hosting_ssl_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    $form['port']['ssl'] = array('#type' => 'checkbox', '#title' => 'Enable SSL encryption', '#default_value' => $form['#node']->ssl, '#weight' => 4, '#attributes' => array('onClick' => 'if (!this.checked) { $("#edit-ssl-redirect").attr("checked", this.checked) };'),);
    $form['port']['ssl_redirect'] = array('#type' => 'checkbox', '#title' => 'Redirect HTTP to HTTPS', '#default_value' => $form['#node']->ssl_redirect, '#weight' => 5, '#attributes' => array('onClick' => 'if (this.checked) { $("#edit-ssl").attr("checked", this.checked);}'),);
    $form['port']['#title'] = t("Port and encryption");
  }
}

function hosting_ssl_nodeapi(&$node, $op, $teaser, $page) {
  switch($op) {
    case 'view':
      if ($node->type == 'site') {
        $node->content['info']['ssl'] = array('#type' => 'item', '#title' => 'SSL encryption', '#value' => ( $node->ssl ? t('Enabled') : t('Disabled') ));
      }
      break;
  }
}
